resources:
  repositories:
    - repository: azure-devops-tools
      type: github
      endpoint: 'github-nla-acmecorp-nexus'
      name: 'nexus-link/nexus-azure-devops-tools'
      ref: 'refs/heads/master'

trigger:
  branches:
    include:
      - master
      - dev
  paths:
    include:
      - 'src/AcmeCorp.BusinessApi.Libraries.Core/*'

jobs:
  - template: 'templates/netcore/v1/jobs/nuget.yml@azure-devops-tools'
    parameters:
      nugetProjectsPath: 'src/AcmeCorp.BusinessApi.Libraries.Core/*.csproj'
      testProjectsPath: 'test/Core.Test/*.csproj'
      publishVstsFeed: '7dea9355-6ff6-4e1e-9d36-7617d5d074ab'
