resources:
  repositories:
    - repository: azure-devops-tools
      type: github
      endpoint: 'github-nla-acmecorp-nexus'
      name: 'nexus-link/nexus-azure-devops-tools'
      ref: 'refs/heads/master'

trigger:
  branches:
    include:
      - master
      - dev
  paths:
    include:
      - 'src/AcmeCorp.BusinessApi.Libraries.Sdk/*'

jobs:
  - template: 'templates/netcore/v1/jobs/nuget.yml@azure-devops-tools'
    parameters:
      nugetProjectsPath: 'src/AcmeCorp.BusinessApi.Libraries.Sdk/*.csproj'
      testProjectsPath: 'test/Sdk.Test/*.csproj'
      publishVstsFeed: 'AcmeCorpNexus'
